apiVersion: apps/v1
kind: Deployment
metadata:
  name: sumitapp
  labels:
    app: sumitapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: sumitapp
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: sumitapp
    spec:
      containers:
      - name: sumitapp
        image: sumitapp:0.0.1
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: sumitapp
