apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: sumitapp
  labels:
    app: sumitapp
spec:
  type: ClusterIP
  selector:
    app: sumitapp
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
