apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sumitapp
  namespace: default
spec:
  interval: 15m
  path: "./sumit_flex/fluxcd/repositories/sumitapp/deploy "
  prune: true
  sourceRef:
    kind: GitRepository
    name: sumitapp
