apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sumitapp
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/sumitch50/sumit_flex
